# Generated by Django 5.1.5 on 2025-01-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_miembro_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="puesto",
            name="nivel",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="miembro",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/empleados"
            ),
        ),
    ]
