# Generated by Django 5.1.5 on 2025-01-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_puesto_nivel_alter_miembro_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="miembro",
            name="descripcion_corta",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="mostrar_en_inicio",
            field=models.BooleanField(default=False),
        ),
    ]
