# Generated by Django 5.1.5 on 2025-01-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_miembro_descripcion_corta_miembro_mostrar_en_inicio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
