# Generated by Django 5.1.5 on 2025-02-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_servicio_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/servicios"
                    ),
                ),
            ],
        ),
    ]
