# Generated by Django 5.1.5 on 2025-02-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="sitio_web",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
