# Generated by Django 5.1.5 on 2025-02-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_partner_sitio_web"),
    ]

    operations = [
        migrations.AddField(
            model_name="miembro",
            name="descripcion_corta_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="descripcion_corta_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="descripcion_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="descripcion_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="nombre_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="miembro",
            name="nombre_es",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="descripcion_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="descripcion_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="nombre_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="nombre_es",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="puesto",
            name="descripcion_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puesto",
            name="descripcion_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puesto",
            name="nombre_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="puesto",
            name="nombre_es",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicio",
            name="descripcion_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicio",
            name="descripcion_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicio",
            name="nombre_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="servicio",
            name="nombre_es",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
