# Generated by Django 5.1.5 on 2025-02-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_miembro_descripcion_corta_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="miembro",
            name="nombre_en",
        ),
        migrations.RemoveField(
            model_name="miembro",
            name="nombre_es",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="nombre_en",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="nombre_es",
        ),
    ]
