# Generated by Django 5.1.5 on 2025-02-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_comentario"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenesDeComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/comentarios"
                    ),
                ),
            ],
        ),
    ]
