# Generated by Django 5.1.6 on 2025-02-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_imagenesdecomentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="respuesta_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas",
                to="website.comentario",
            ),
        ),
    ]
